version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - mkdir myapp
      - cd myapp
      
  build:
    commands:
      - echo Build started on 'date'
      - npm run build

artifacts:
  files:
    - '**/*'
    #- "myapp/build/**/*"
  base-directory: 'myapp/build'
  #discard-paths: yes